workflows:
  ios-capacitor:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Rezerwacja24
    
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "pl.rezerwacja24.app"
      node: 18
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Fetch signing files
        script: |
          # List available certificates
          echo "=== Certificates in keychain ==="
          app-store-connect certificates list || true
          
          # List available profiles  
          echo "=== Profiles in Apple ==="
          app-store-connect profiles list || true
          
          # Fetch signing files
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --strict-match-identifier || echo "Fetch failed, trying without strict match..."
          
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create || true
            
          # Add certs and profiles
          keychain add-certificates || true
          xcode-project use-profiles || true
          
          # Debug: show what we have
          echo "=== Provisioning profiles installed ==="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ || true
      
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      
      - name: Build web assets
        script: |
          cd frontend
          npm run build
          npx cap sync ios
      
      - name: Install CocoaPods dependencies
        script: |
          cd frontend/ios/App
          pod install
      
      - name: Build iOS app
        script: |
          cd frontend/ios/App
          
          # Build without signing first
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -destination 'generic/platform=iOS' \
            archive \
            CODE_SIGNING_ALLOWED=NO
          
          # Then export with signing
          cat > ExportOptions.plist << 'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store-connect</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>uploadSymbols</key>
            <true/>
          </dict>
          </plist>
          PLIST
          
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates
    
    artifacts:
      - frontend/ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - hubert.samek05@gmail.com
        notify:
          success: true
          failure: true
