workflows:
  ios-capacitor:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Rezerwacja24
    
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "pl.rezerwacja24.app"
      node: 18
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --strict-match-identifier --create
          keychain add-certificates
          xcode-project use-profiles --export-options-plist=/Users/builder/export_options.plist
      
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      
      - name: Build web assets
        script: |
          cd frontend
          npm run build
          npx cap sync ios
      
      - name: Install CocoaPods dependencies
        script: |
          cd frontend/ios/App
          pod install
      
      - name: Build iOS app
        script: |
          cd frontend/ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App
    
    artifacts:
      - frontend/ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - hubert.samek05@gmail.com
        notify:
          success: true
          failure: true
