workflows:
  ios-capacitor:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Rezerwacja24
    environment:
      vars:
        BUNDLE_ID: pl.rezerwacja24.app
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up signing
        script: |
          keychain initialize
          
          # Create certificate if needed
          app-store-connect certificates create --type IOS_DISTRIBUTION --save || echo "Certificate exists"
          
          # Create profile if needed  
          app-store-connect profiles create \
            --name "Rezerwacja24 AppStore" \
            --type IOS_APP_STORE \
            --bundle-id-identifier $BUNDLE_ID \
            --certificate-key-id $(app-store-connect certificates list --type IOS_DISTRIBUTION | grep -o '"id": "[^"]*"' | head -1 | cut -d'"' -f4) \
            --save || echo "Profile exists"
          
          # Download everything
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
          
          # Add to keychain
          keychain add-certificates
          xcode-project use-profiles
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      - name: Build web assets
        script: |
          cd frontend
          npm run build
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd frontend/ios/App
          pod install
      - name: Build IPA
        script: |
          cd frontend/ios/App
          xcode-project build-ipa --workspace App.xcworkspace --scheme App
    artifacts:
      - frontend/ios/App/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - hubert.samek05@gmail.com
        notify:
          success: true
          failure: true
