workflows:
  ios-capacitor:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Rezerwacja24
    
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "pl.rezerwacja24.app"
      node: 18
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --strict-match-identifier --create
          keychain add-certificates
          xcode-project use-profiles --export-options-plist=/Users/builder/export_options.plist
      
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      
      - name: Build web assets
        script: |
          cd frontend
          npm run build
          npx cap sync ios
      
      - name: Install CocoaPods dependencies
        script: |
          cd frontend/ios/App
          pod install
      
      - name: Build iOS app
        script: |
          cd frontend/ios/App
          
          # Get provisioning profile info
          PROFILE_PATH=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision 2>/dev/null | head -1)
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          TEAM_ID=$(/usr/libexec/PlistBuddy -c "Print :TeamIdentifier:0" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c "Print Name" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          
          echo "Profile UUID: $PROFILE_UUID"
          echo "Team ID: $TEAM_ID"
          echo "Profile Name: $PROFILE_NAME"
          
          # Update project.pbxproj with correct values
          sed -i '' "s/DEVELOPMENT_TEAM = \"\"/DEVELOPMENT_TEAM = $TEAM_ID/g" App.xcodeproj/project.pbxproj
          sed -i '' "s/PROVISIONING_PROFILE_SPECIFIER = \"\"/PROVISIONING_PROFILE_SPECIFIER = \"$PROFILE_NAME\"/g" App.xcodeproj/project.pbxproj
          
          # Create export options plist
          cat > ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store-connect</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>uploadSymbols</key>
              <true/>
              <key>provisioningProfiles</key>
              <dict>
                  <key>pl.rezerwacja24.app</key>
                  <string>$PROFILE_NAME</string>
              </dict>
          </dict>
          </plist>
          EOF
          
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME" \
            CODE_SIGN_IDENTITY="Apple Distribution"
          
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist
    
    artifacts:
      - frontend/ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - hubert.samek05@gmail.com
        notify:
          success: true
          failure: true
