workflows:
  ios-capacitor:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Rezerwacja24
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: pl.rezerwacja24.app
        TEAM_ID: "22MYTLYQ6T"
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up signing
        script: |
          keychain initialize
          
          # Decode and import certificate
          echo "$CM_CERTIFICATE" | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password "$CM_CERTIFICATE_PASSWORD"
          
          # Fetch profile from Apple
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create || true
          
          # Use profiles
          xcode-project use-profiles || true
          
          echo "=== Certificates ==="
          security find-identity -v -p codesigning
          echo "=== Profiles ==="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: Install dependencies
        script: |
          cd frontend && npm install
      - name: Build web assets
        script: |
          cd frontend && npm run build && npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd frontend/ios/App && pod install
      - name: Build IPA
        script: |
          cd frontend/ios/App
          
          # Get certificate and profile info
          CERT_NAME=$(security find-identity -v -p codesigning | grep "Apple Distribution" | head -1 | sed 's/.*"\(.*\)".*/\1/')
          PROFILE_PATH=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision 2>/dev/null | head -1)
          
          if [ -z "$PROFILE_PATH" ]; then
            echo "ERROR: No provisioning profile found!"
            exit 1
          fi
          
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c "Print Name" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          
          echo "Certificate: $CERT_NAME"
          echo "Profile: $PROFILE_NAME"
          echo "Team: $TEAM_ID"
          
          # Build with signing
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -destination 'generic/platform=iOS' \
            archive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="$CERT_NAME" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME" \
            DEVELOPMENT_TEAM="$TEAM_ID"
          
          # Export
          xcode-project build-ipa \
            --archive-path build/App.xcarchive \
            --export-options-plist=/Users/builder/export_options.plist || \
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist /Users/builder/export_options.plist
    artifacts:
      - frontend/ios/App/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - hubert.samek05@gmail.com
        notify:
          success: true
          failure: true
