workflows:
  ios-capacitor:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Rezerwacja24
    environment:
      vars:
        BUNDLE_ID: pl.rezerwacja24.app
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up signing
        script: |
          keychain initialize
          
          # Create certificate if needed
          app-store-connect certificates create --type IOS_DISTRIBUTION --save || echo "Certificate exists"
          
          # Create profile if needed  
          app-store-connect profiles create \
            --name "Rezerwacja24 AppStore" \
            --type IOS_APP_STORE \
            --bundle-id-identifier $BUNDLE_ID \
            --certificate-key-id $(app-store-connect certificates list --type IOS_DISTRIBUTION | grep -o '"id": "[^"]*"' | head -1 | cut -d'"' -f4) \
            --save || echo "Profile exists"
          
          # Download everything
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
          
          # Add to keychain
          keychain add-certificates
          xcode-project use-profiles
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      - name: Build web assets
        script: |
          cd frontend
          npm run build
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd frontend/ios/App
          pod install
      - name: Build IPA
        script: |
          cd frontend/ios/App
          
          # Get signing identity
          CERT_NAME=$(security find-identity -v -p codesigning | grep "Apple Distribution" | head -1 | sed 's/.*"\(.*\)".*/\1/')
          echo "Certificate: $CERT_NAME"
          
          # Get profile
          PROFILE_PATH=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision 2>/dev/null | head -1)
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c "Print Name" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          TEAM_ID=$(/usr/libexec/PlistBuddy -c "Print :TeamIdentifier:0" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          echo "Profile: $PROFILE_NAME ($PROFILE_UUID)"
          echo "Team: $TEAM_ID"
          
          # Archive with signing
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -destination 'generic/platform=iOS' \
            archive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="$CERT_NAME" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME" \
            DEVELOPMENT_TEAM="$TEAM_ID"
          
          # Export
          echo '<?xml version="1.0" encoding="UTF-8"?>' > ExportOptions.plist
          echo '<plist version="1.0"><dict>' >> ExportOptions.plist
          echo "<key>method</key><string>app-store-connect</string>" >> ExportOptions.plist
          echo "<key>teamID</key><string>$TEAM_ID</string>" >> ExportOptions.plist
          echo "<key>signingStyle</key><string>manual</string>" >> ExportOptions.plist
          echo "<key>signingCertificate</key><string>$CERT_NAME</string>" >> ExportOptions.plist
          echo "<key>provisioningProfiles</key><dict>" >> ExportOptions.plist
          echo "<key>pl.rezerwacja24.app</key><string>$PROFILE_NAME</string>" >> ExportOptions.plist
          echo "</dict></dict></plist>" >> ExportOptions.plist
          
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - frontend/ios/App/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - hubert.samek05@gmail.com
        notify:
          success: true
          failure: true
